#pragma once

enum Controls
{
	ESCAPE,
	CAMERA_MOVE_LEFT,
	CAMERA_MOVE_RIGHT,
	CAMERA_MOVE_FORWARD,
	CAMERA_MOVE_BACKWARD,
	CAMERA_LOOK_LEFT,
	CAMERA_LOOK_RIGHT,
	CAMERA_LOOK_UP,
	CAMERA_LOOK_DOWN, 
	TOGGLE_RASTERIZER_STATE
};